apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.service.name }}
  annotations:
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.route53url }}
  namespace: {{ .Values.app.ns.name }}
  labels:
    app: nclouds
    type: service
    name: davidjgg-svc
spec:
  type: {{ .Values.service.type }}
  selector:
    app: nclouds
    type: pod
    name: sample-app
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.image.containerPort }}