# Default values for david-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 3

app:
  deployment:
    name: nclouds-davidjgg-deploy
  service:
    name: nclouds-davidjgg-svc
  ns:
    name: davidjgg-ns

image:
  name: davidjgg-app
  repository: ncloudspublic/sample-app
  pullPolicy: IfNotPresent
  containerPort: 3000
  env:
    name: APPLICATION
    value: nclouds-sample-app

service:
  type: LoadBalancer
  port: 3000


resources:
  lim:
    mem: 256Mi
    cpu: 500m
  req:
    mem: 128Mi
    cpu: 250m
    

